title: 基于 objc 的 iOS 开发教程
url: https://professordeng.com            # 网站域名
baseurl: /ios-objc                        # 站点路径
description: ProfessorDeng                # 网站描述
img: /ios-objc/img                           # 图片路径

# 插件
plugins:
  - jekyll-feed                           # 订阅插件
  - jekyll-sitemap                        # 站点地图
  - jemoji                                # GitHub 表情
  - jekyll-avatar                         # GitHub 头像
  - jekyll-mentions                       # GitHub 提名
  
# MathJax 提供数学渲染支持
math: "<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {inlineMath: [ ['$','$'] ]}});</script><script src=\"//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>"

